### ISSUE TITLE
Crashing while running tests sometimes: Errno::ENOENT: No such file or directory - getcwd

### ISSUE THREAD

**Issue by Doldrums** [cqfn/pdd#178]
### Description
Actually, seems to be some kind of bug like rarely there is an issue while executing `bundle exec rake`  in particular while executing `TestSources#test_ignores_binary_files:`

### Trace is the following:
``` 31mError:
TestSources#test_ignores_binary_files:
Errno::ENOENT: No such file or directory - getcwd
    /home/r/repo/test/test_sources.rb:50:in `pwd'
    /home/r/repo/test/test_sources.rb:50:in `block (2 levels) in test_ignores_binary_files'
    /home/r/repo/test/test_sources.rb:50:in `each'
    /home/r/repo/test/test_sources.rb:50:in `block in test_ignores_binary_files'
    /home/r/repo/test/test_sources.rb:125:in `block in in_temp'
    /usr/local/rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/tmpdir.rb:89:in `mktmpdir'
    /home/r/repo/test/test_sources.rb:119:in `in_temp'
    /home/r/repo/test/test_sources.rb:41:in `test_ignores_binary_files'
0m

rails test home/r/repo/test/test_sources.rb:39

sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
32m.0msh: 0: getcwd() failed: No such file or directory
32m.0msh: 0: getcwd() failed: No such file or directory
32m.0m 
```

### Example:
https://github.com/cqfn/pdd/pull/177#issuecomment-929938609

**Comment by Doldrums** [comment]
@rultor hello

**Comment by Doldrums** [comment]
@rultor hello

**Comment by yegor256** [comment]
@mbao01 can you help here please?
